# set(CMAKE_MODULE_PATH "$ENV{HOME}/.cmake/packages")
# include(WarningFlagsCXX OPTIONAL)
add_compile_options(-Weffc++)
add_compile_options(-Wcast-align -Wcast-qual)
add_compile_options(-Wconversion)
add_compile_options(-Wsign-conversion)
add_compile_options(-Wdisabled-optimization)
add_compile_options(-Wdouble-promotion)
add_compile_options(-Wfloat-equal)
add_compile_options(-Wformat=2)
add_compile_options(-Wshadow)
