# set(CMAKE_MODULE_PATH "$ENV{HOME}/.cmake/packages")
# include(WarningFlagsCXX OPTIONAL)
add_compile_options(-Weffc++)
add_compile_options(-Wcast-align -Wcast-qual)
add_compile_options(-Wconversion)
add_compile_options(-Wno-sign-conversion)
add_compile_options(-Wdisabled-optimization)
add_compile_options(-Wdouble-promotion)
add_compile_options(-Wfloat-equal)
add_compile_options(-Wformat=2)
add_compile_options(-Winit-self)
add_compile_options(-Wmissing-include-dirs)
add_compile_options(-Wold-style-cast)
add_compile_options(-Woverloaded-virtual)
add_compile_options(-Wredundant-decls)
add_compile_options(-Wshadow)
add_compile_options(-Wstrict-aliasing=1)
add_compile_options(-Wstrict-overflow=5)
add_compile_options(-Wswitch-default)
