[colors]
ansi = [
  "#252525",
  "#ed4a46",
  "#70b433",
  "#dbb32d",
  "#368aeb",
  "#eb6eb7",
  "#3fc5b7",
  "#777777",
]
background = "#181818"
brights = [
  "#3b3b3b",
  "#ff5e56",
  "#83c746",
  "#efc541",
  "#4f9cfe",
  "#ff81ca",
  "#56d8c9",
  "#dedede",
]
cursor_bg = "#dedede"
cursor_border = "#dedede"
cursor_fg = "#181818"
foreground = "#b9b9b9"

[colors.indexed]

[metadata]
aliases = []
name = "Selenized Black (Gogh)"
origin_url = "https://github.com/Gogh-Co/Gogh"
