[colors]
ansi = [
  "#ebebeb",
  "#d6000c",
  "#1d9700",
  "#c49700",
  "#0064e4",
  "#dd0f9d",
  "#00ad9c",
  "#878787",
]
background = "#ffffff"
brights = [
  "#cdcdcd",
  "#bf0000",
  "#008400",
  "#af8500",
  "#0054cf",
  "#c7008b",
  "#009a8a",
  "#282828",
]
cursor_bg = "#282828"
cursor_border = "#282828"
cursor_fg = "#ffffff"
foreground = "#474747"

[colors.indexed]

[metadata]
aliases = []
name = "Selenized White (Gogh)"
origin_url = "https://github.com/Gogh-Co/Gogh"
