cache-dir = "~/.cache/ruff"

[lint]
select = [
  "F",
  "E",
  "W",
  "C90",
  "I",
  "N",
  "D2",
  "D3",
  "D4",
  "UP",
  "YTT",
  "ANN0",
  "ANN2",
  "ASYNC",
  "S",
  "BLE",
  "FBT",
  "B",
  "A",
  "C4",
  "DTZ",
  "EM",
  "EXE",
  "ICN",
  "LOG",
  "G",
  "PIE",
  "PT",
  "Q",
  "RSE",
  "RET",
  "SLF",
  "SLOT",
  "SIM",
  "TID",
  "TCH",
  "ARG",
  "PTH",
  "PD",
  "PL",
  "TRY",
  "FLY",
  "NPY",
  "PERF",
  "RUF",
]
ignore = [
  "D203",
  "D213",
]
