cache-dir = "~/.cache/ruff"
select = [
  "F",
  "E",
  "W",
  "C90",
  "I",
  "N",
  "D",
  "UP",
  "S",
  "B",
  "A",
  "C4",
  "EXE",
  "PT",
  "RET",
  "SIM",
  "PTH",
  "PD",
  "PL",
  "FLY",
  "NPY",
  "RUF",
]
